### ISSUE TITLE
dead link to plugin ZIP in Dockerfile

### ISSUE THREAD

**Issue by rursprung** [opendistro-for-elasticsearch/cross-cluster-replication#3]
the `Dockerfile` contains a dead link to a ZIP file for this plugin:
https://github.com/opendistro-for-elasticsearch/cross-cluster-replication/blob/e89a9dd57895b0bd3f813afd0a8ee17b5196d16e/examples/sample/open-distro-for-es-with-replication/Dockerfile#L15

thus it won't work.

see also: https://discuss.opendistrocommunity.dev/t/unable-to-install-ccr-plugin-or-install-via-example/6429

**Comment by krishna-ggk** [comment]
Thanks a lot for reporting this.

Apologies for the delay. Our preparation to make CCR part of OpenSearch resulted in few deadlinks.

We have fixed this now.

Please reopen if you still see the issue.
